# docker compose for my django project that has sqlite as database

version: '3'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "sqlite"
    volumes:
      - ./db.sqlite3:/db.sqlite3