# Generated by Django 4.2.9 on 2024-02-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.URLField(default='https://example.com/default-image.jpg')),
                ('time', models.CharField(max_length=100, null=True)),
                ('portions', models.IntegerField(null=True)),
                ('instructions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='groceryapp.RecipeIngredient', to='groceryapp.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groceryapp.mealtype'),
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groceryapp.category')),
            ],
        ),
    ]
