# Generated by Django 4.2.9 on 2024-02-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
