# Generated by Django 4.2.9 on 2024-02-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
