# Generated by Django 4.2.9 on 2024-02-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0004_alter_groceryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
