# Generated by Django 4.2.9 on 2024-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0007_groceryitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='unit_of_measure',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
