# Generated by Django 4.2.9 on 2024-02-11 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0008_alter_groceryitem_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date_bought',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
