# Generated by Django 4.2.9 on 2024-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_groceryitem_date_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
